# Generated by Django 4.0.1 on 2022-01-28 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('fullname', models.CharField(max_length=50, verbose_name='Name')),
                ('dept', models.CharField(max_length=50, verbose_name='Department')),
                ('design', models.CharField(max_length=50, verbose_name='Designation')),
                ('mac', models.CharField(max_length=14, verbose_name='Mac Address')),
                ('device', models.CharField(choices=[('Smartphone', 'Smartphone'), ('Laptop', 'Laptop'), ('Tablet', 'Tablet'), ('PC', 'PC'), ('Desktop', 'Desktop')], max_length=15, verbose_name='Device')),
                ('others', models.CharField(blank=True, max_length=15, null=True, verbose_name='Specify')),
                ('email', models.EmailField(max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='Email')),
                ('phone', models.DecimalField(decimal_places=0, max_digits=11, unique=True, verbose_name='Phone No')),
                ('facname', models.CharField(max_length=10, verbose_name='Faculty Name')),
                ('upload', models.ImageField(upload_to='', verbose_name='Signature')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
