# Generated by Django 4.0.1 on 2022-02-07 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='adminlogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fnames', models.CharField(max_length=50)),
                ('fdepartment', models.CharField(max_length=50)),
                ('fdesignation', models.CharField(max_length=50)),
                ('fmacadd', models.CharField(max_length=14)),
                ('fsystem', models.CharField(choices=[('Smartphone', 'Smartphone'), ('Laptop', 'Laptop'), ('Tablet', 'Tablet'), ('PC', 'PC'), ('Desktop', 'Desktop')], max_length=15)),
                ('fothers', models.CharField(blank=True, default='None', max_length=15, null=True)),
                ('femail', models.EmailField(max_length=50, unique=True)),
                ('fphone', models.IntegerField(max_length=11, unique=True)),
                ('ffacultys', models.CharField(max_length=10)),
                ('fupload', models.ImageField(upload_to='')),
                ('fdate', models.DateTimeField(auto_now_add=True)),
                ('ftype', models.CharField(max_length=10)),
                ('fmark', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names2', models.CharField(max_length=50)),
                ('email2', models.EmailField(max_length=50, unique=True)),
                ('macadd2', models.CharField(max_length=14)),
                ('kind', models.CharField(max_length=8)),
                ('marked', models.CharField(max_length=8)),
                ('timed', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snames', models.CharField(max_length=50)),
                ('scourse', models.CharField(choices=[('BSCE', 'BSCE'), ('BSEE', 'BSEE'), ('BSME', 'BSME'), ('BET-ET', 'BET-ET'), ('BET-ESET', 'BET-ESET'), ('BET-COET', 'BET-COET'), ('BET-CT', 'BET-CT'), ('BET-AT', 'BET-AT'), ('BET-MT', 'BET-MT'), ('BET-PPT', 'BET-PPT'), ('BET-ICT', 'BET-ICT'), ('BET-HE', 'BET-HE'), ('BET-AU', 'BET-AU'), ('BET-EI', 'BET-EI'), ('BET-E', 'BET-E'), ('BET-HVACT', 'BET-HVACT'), ('BET-CP', 'BET-CP')], max_length=50)),
                ('ssemester', models.CharField(choices=[('First Semester', 'First Semester'), ('Second Semester', 'Second Semester'), ('Others...', 'Others...')], max_length=20)),
                ('stupid', models.CharField(max_length=12)),
                ('sornum', models.IntegerField()),
                ('sphone', models.IntegerField(max_length=11, unique=True)),
                ('ssystem', models.CharField(choices=[('Smartphone', 'Smartphone'), ('Laptop', 'Laptop'), ('Tablet', 'Tablet'), ('PC', 'PC'), ('Desktop', 'Desktop')], max_length=15)),
                ('sothers', models.CharField(blank=True, max_length=15, null=True)),
                ('smacadd', models.CharField(max_length=14)),
                ('semail', models.EmailField(max_length=50, unique=True)),
                ('sresidAdd', models.CharField(max_length=200)),
                ('supload', models.ImageField(upload_to='')),
                ('stype', models.CharField(max_length=10)),
                ('smark', models.CharField(max_length=10)),
            ],
        ),
    ]
