# Generated by Django 4.0.3 on 2022-03-25 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Wifi_App', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
