# Generated by Django 4.0.1 on 2022-02-07 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wifi_App', '0002_alter_faculty_fphone_alter_student_sphone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='id',
        ),
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.AlterField(
            model_name='faculty',
            name='femail',
            field=models.EmailField(max_length=50, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='stupid',
            field=models.CharField(max_length=12, primary_key=True, serialize=False),
        ),
    ]
