# Generated by Django 4.0.1 on 2022-02-07 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wifi_App', '0003_remove_faculty_id_remove_student_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='semail',
            field=models.EmailField(max_length=50, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='stupid',
            field=models.CharField(max_length=12),
        ),
    ]
